### PR TITLE
Fill

### PR DESCRIPTION
**Pull request by Ehawk82**
sent everything over to main

### CODE REVIEW

**Review by StoneCypher — APPROVED** [review]

**Comment by StoneCypher** [comment]
This is ready to merge.  I need you to merge master first please

**Comment by StoneCypher** [comment]
```
git fetch --all
git checkout master
git pull
git checkout your_branch
git merge master
npm run build
```

If the tests still pass, update the branch after that and I'll merge

**Comment by Ehawk82** [comment]
$ git checkout master
         error: pathspec 'master' did not match any file(s) known to
git

**Comment by StoneCypher** [comment]
merge main*

**Comment by StoneCypher** [comment]
look up how to do it.  don't just try once and wait for me to tell you how

**Review by Ehawk82 — COMMENTED** [review]
master -> main merger was smooth, build showed no errors

**Comment by StoneCypher** [comment]
You didn't update the results in `dist/` after the build, so they're still in conflict

Please add the post-builds

**Comment by StoneCypher** [comment]
oh, you're still saying master -> main

master is the old branch.  i renamed it main a couple months ago because of the desire to eliminate things called master

if you merged something called master it's probably historic and probably had no impact

**Comment by StoneCypher** [comment]
i was mistaken to say master earlier; it's main

i just call them master by habit.  trying to change

**Comment by StoneCypher** [comment]
i could be talking you through this if you were on chat

**Comment by StoneCypher** [comment]
* ✔️ Appears to support [`Array.fill/1` API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill)
* ✔️ Tests are adequate
* ✔️ Don't see any bugs
* ✔️ Merged with `main`

In it goes

**Pull request merged**
